name: Build Enmity and Inject Rosiecord
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Enmity and Inject Rosiecord
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Retrieve version
        run: |
          echo $(ls | grep Discord | sed -e s/[^0-9.]//g | sed -e s/[/.+?\./]//g)
        id: version
      - name: Run Main Shell Script
        id: shell_script
        run: sh ./patch.sh
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          tag_name: Rosiecord v${{ steps.version.outputs.value }}
          files: dist/*