name: Build Enmity and Inject Rosiecord
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Enmity and Inject Rosiecord
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Retrieve version
        run: |
          cd ./ipas
          echo "::set-output name=DISCORD_VERSION::$(ls | grep Discord | sed -e s/[^0-9.]//g | sed -e s/[/.+?\./]//g)"   
        id: version

      - name: Run Main Shell Script
        id: shell_script
        run: sh ./patch.sh
        
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: rosiecord_v${{ steps.version.outputs.DISCORD_VERSION }}
          title: Rosiecord v${{ steps.version.outputs.DISCORD_VERSION }}
          files: dist/*.ipa